var slider = tns({
    container: '.services-slider',
    'slideBy': 1,
    'speed' : 400,
    'nav': true,
    'navPosition': 'bottom',
    'items': 1.5,
    gutter: 20,
    // 'autoplay': true,
    'controlsPosition': 'bottom',
    'controlsText': ['<', '>'],
    'autoplayTimeout' : 3000,
    'autoplayHoverPause': true,
    autoplayButtonOutput: false,
})